version: '3.9'

services:

  db:
    image: postgres:latest
    container_name: quotes-postgres
    restart: always
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: aN9e94poEi
      POSTGRES_DB: quotes_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./db_data
        target: /var/lib/postgresql/data
