version: '3.9'

services:

  web:
    build: .
    command: gunicorn quotes_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=quotes_project.settings

  db:
    image: postgres:latest
    container_name: quotes-postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: aN9e94poEi
      POSTGRES_DB: quotes_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./db_data
        target: /var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
